# Generated by Django 4.2.1 on 2023-05-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_1', models.CharField(max_length=255)),
                ('str_2', models.CharField(max_length=255)),
                ('str_3', models.CharField(max_length=255)),
                ('str_4', models.CharField(max_length=255)),
                ('str_5', models.CharField(max_length=255)),
            ],
        ),
    ]
